version: '3.8'

services:
  app:
    build:
      context: .
    container_name: URLShortenerService2
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://mysql:3306/demo
      DB_USER: developer
      DB_PASS: password
    ports:
      - "8004:8080"

  mysql:
    image: 'mysql:latest'
    container_name: mysqlDb
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER -p$$MYSQL_PASSWORD" ]
      interval: 30s
      timeout: 10s
      retries: 5

  authservice:
    image: ghcr.io/chatgut/authservice2:latest
    container_name: auth
    depends_on:
      - auth-DB
    environment:
        DB_URL: auth-DB:3306/auth-DB1
        DB_USER: developer
        DB_PASS: password
    ports:
      - "8003:8080"
  auth-DB:
    image: 'mysql:latest'
    container_name: auth-DB1
    volumes:
     - dbAuth:/var/lib/mysql
    environment:
      MYSQL_DATABASE: auth-DB1
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
volumes:
  db:
  dbAuth: